version: "3.9"

services:

  web:
    build: code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      DJANGO_SECRET: "${DJANGO_SECRET}"
    restart: 'always'
    volumes:
      - ./code:/code
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
#    environment:
    links:
      - mariadb
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: 'always'
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
    depends_on:
      - web
    links:
      - web

  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    volumes:
      - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
      - "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    expose:
      - 3306
